/* Generated by Yosys 0.46+124 (git sha1 8c2d1a16d, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module adder32(a, b, cin, s, cout);
  input [31:0] a;
  wire [31:0] a;
  input [31:0] b;
  wire [31:0] b;
  wire c1;
  wire c2;
  wire c3;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [31:0] s;
  wire [31:0] s;
  adder8 Add1 (
    .a(a[7:0]),
    .b(b[7:0]),
    .cin(cin),
    .cout(c1),
    .s(s[7:0])
  );
  adder8 Add2 (
    .a(a[15:8]),
    .b(b[15:8]),
    .cin(c1),
    .cout(c2),
    .s(s[15:8])
  );
  adder8 Add3 (
    .a(a[23:16]),
    .b(b[23:16]),
    .cin(c2),
    .cout(c3),
    .s(s[23:16])
  );
  adder8 Add4 (
    .a(a[31:24]),
    .b(b[31:24]),
    .cin(c3),
    .cout(cout),
    .s(s[31:24])
  );
endmodule

module adder4(s, cout, a, b, cin);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [3:0] s;
  wire [3:0] s;
  NAND2_X1 _15_ (
    .A1(a[3]),
    .A2(b[3]),
    .ZN(_00_)
  );
  AND2_X1 _16_ (
    .A1(a[2]),
    .A2(b[2]),
    .ZN(_01_)
  );
  NAND2_X1 _17_ (
    .A1(a[1]),
    .A2(b[1]),
    .ZN(_02_)
  );
  AND2_X1 _18_ (
    .A1(a[0]),
    .A2(b[0]),
    .ZN(_03_)
  );
  OR2_X1 _19_ (
    .A1(a[0]),
    .A2(b[0]),
    .ZN(_04_)
  );
  XNOR2_X1 _20_ (
    .A(a[0]),
    .B(b[0]),
    .ZN(_05_)
  );
  AOI21_X1 _21_ (
    .A(_03_),
    .B1(_04_),
    .B2(cin),
    .ZN(_06_)
  );
  NOR2_X1 _22_ (
    .A1(a[1]),
    .A2(b[1]),
    .ZN(_07_)
  );
  XOR2_X1 _23_ (
    .A(a[1]),
    .B(b[1]),
    .Z(_08_)
  );
  OAI21_X1 _24_ (
    .A(_02_),
    .B1(_06_),
    .B2(_07_),
    .ZN(_09_)
  );
  OR2_X1 _25_ (
    .A1(a[2]),
    .A2(b[2]),
    .ZN(_10_)
  );
  XNOR2_X1 _26_ (
    .A(a[2]),
    .B(b[2]),
    .ZN(_11_)
  );
  AOI21_X1 _27_ (
    .A(_01_),
    .B1(_09_),
    .B2(_10_),
    .ZN(_12_)
  );
  NOR2_X1 _28_ (
    .A1(a[3]),
    .A2(b[3]),
    .ZN(_13_)
  );
  XOR2_X1 _29_ (
    .A(a[3]),
    .B(b[3]),
    .Z(_14_)
  );
  OAI21_X1 _30_ (
    .A(_00_),
    .B1(_12_),
    .B2(_13_),
    .ZN(cout)
  );
  XNOR2_X1 _31_ (
    .A(cin),
    .B(_05_),
    .ZN(s[0])
  );
  XNOR2_X1 _32_ (
    .A(_06_),
    .B(_08_),
    .ZN(s[1])
  );
  XNOR2_X1 _33_ (
    .A(_09_),
    .B(_11_),
    .ZN(s[2])
  );
  XNOR2_X1 _34_ (
    .A(_12_),
    .B(_14_),
    .ZN(s[3])
  );
endmodule

module adder64(a, b, cin, s, cout);
  input [63:0] a;
  wire [63:0] a;
  input [63:0] b;
  wire [63:0] b;
  wire c1;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [63:0] s;
  wire [63:0] s;
  adder32 Add1 (
    .a(a[31:0]),
    .b(b[31:0]),
    .cin(cin),
    .cout(c1),
    .s(s[31:0])
  );
  adder32 Add2 (
    .a(a[63:32]),
    .b(b[63:32]),
    .cin(c1),
    .cout(cout),
    .s(s[63:32])
  );
endmodule

module adder8(a, b, cin, s, cout);
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  wire c1;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [7:0] s;
  wire [7:0] s;
  adder4 Add1 (
    .a(a[3:0]),
    .b(b[3:0]),
    .cin(cin),
    .cout(c1),
    .s(s[3:0])
  );
  adder4 Add2 (
    .a(a[7:4]),
    .b(b[7:4]),
    .cin(c1),
    .cout(cout),
    .s(s[7:4])
  );
endmodule
